package sbctl

import (
	"context"
	"errors"
	"fmt"
	"os/exec"
	"path/filepath"
	"sort"
	"time"

	"qingzhou/internal/sbproc"
	"qingzhou/internal/sbver"
	"qingzhou/internal/sshctl"
	"qingzhou/internal/store"
)

type visionRuntimeStore interface {
	SetNodeVisionRuntime(int64, sbver.Info) error
	SetNodeVisionRuntimeError(int64, string) error
}

// This gate is intentionally independent of statsCap, desiredHash, persisted
// version rows and localVersionTTL. P1 Vision must observe installed AND live
// fixed cores afresh on every rebuild, even when generated bytes are unchanged.
func (c *Controller) prepareVisionCapabilities() error {
	c.visionRequired = nil
	c.visionBlocked = nil
	var dependencies map[int64][]int64
	if topology, ok := c.st.(interface {
		RelayUserVisionDependencies() (map[int64][]int64, error)
	}); ok {
		var err error
		dependencies, err = topology.RelayUserVisionDependencies()
		if err != nil {
			return err
		}
	} else if topology, ok := c.st.(interface{ RelayUserVisionServerIDs() ([]int64, error) }); ok {
		ids, err := topology.RelayUserVisionServerIDs()
		if err != nil {
			return err
		}
		dependencies = make(map[int64][]int64, len(ids))
		// Compatibility adapters cannot describe components. Hold their declared
		// Vision nodes together, without touching undeclared/non-Vision machines.
		for _, id := range ids {
			dependencies[id] = ids
		}
	} else {
		return nil
	}
	required := map[int64]bool{}
	for _, ids := range dependencies {
		for _, id := range ids {
			required[id] = true
		}
	}
	ids := make([]int64, 0, len(required))
	for id := range required {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	nodes := make(map[int64]*store.Server, len(ids))
	failures := map[int64]error{}
	for _, id := range ids {
		var sv *store.Server
		var err error
		if id != store.LocalNodeID {
			sv, err = c.st.GetServer(id)
			if err == nil && (sv == nil || !sv.Enabled) {
				err = fmt.Errorf("Vision relay server is missing or disabled")
			}
			if err != nil {
				failures[id] = c.visionProbeFailure(id, err)
				continue
			}
		}
		nodes[id] = sv
		ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
		err = c.verifyVisionCapability(ctx, id, sv, true)
		cancel()
		if err != nil {
			failures[id] = err
		}
	}
	c.visionRequired = nodes
	c.visionBlocked = map[int64]error{}
	for id, needs := range dependencies {
		var errs []error
		for _, requiredID := range needs {
			if err := failures[requiredID]; err != nil {
				errs = append(errs, err)
			}
		}
		if len(errs) != 0 {
			c.visionBlocked[id] = fmt.Errorf("服务器 %d：Vision 线路内核校验失败，保留该服务器当前配置：%w", id, errors.Join(errs...))
			c.markVisionRetry(id)
			c.setStatus(id, "failed", c.visionBlocked[id].Error())
		}
	}
	return c.holdVisionConfigAliases()
}

// Server IDs do not create separate files. If a blocked path shares a local
// config file with node 0 or another local row, allowing that alias to apply
// would overwrite the very bytes the gate promised to preserve. Mirror the
// same lexical path ownership rule as panelPathConflict, in both directions.
func (c *Controller) holdVisionConfigAliases() error {
	if len(c.visionBlocked) == 0 {
		return nil
	}
	servers, err := c.st.ListServers()
	if err != nil {
		return err
	}
	paths := map[string]error{}
	panelPath := c.localConfigPath()
	if err := c.visionBlocked[store.LocalNodeID]; err != nil && panelPath != "" {
		paths[filepath.Clean(panelPath)] = err
	}
	for _, sv := range servers {
		if sv.Enabled && c.visionBlocked[sv.ID] != nil && isLocalHost(sv.Host) {
			paths[filepath.Clean(serverConfigPath(sv))] = c.visionBlocked[sv.ID]
		}
	}
	hold := func(id int64, path string) {
		if c.visionBlocked[id] != nil || path == "" {
			return
		}
		if err := paths[filepath.Clean(path)]; err != nil {
			c.visionBlocked[id] = fmt.Errorf("服务器 %d 与暂停下发的 Vision 线路使用同一个本机配置文件 %s，保留当前配置：%w", id, path, err)
			c.markVisionRetry(id)
			c.setStatus(id, "failed", c.visionBlocked[id].Error())
		}
	}
	hold(store.LocalNodeID, panelPath)
	for _, sv := range servers {
		if sv.Enabled && isLocalHost(sv.Host) {
			hold(sv.ID, serverConfigPath(sv))
		}
	}
	return nil
}

// A recovered version probe is not enough to clear a prior failed apply. Force
// an idempotent apply/health check even if the desired bytes have not changed;
// rememberDesired clears this only after successful readiness acknowledgement.
func (c *Controller) markVisionRetry(id int64) {
	c.desiredMu.Lock()
	defer c.desiredMu.Unlock()
	if c.visionRetry == nil {
		c.visionRetry = map[int64]bool{}
	}
	c.visionRetry[id] = true
}

func (c *Controller) visionProbeFailure(id int64, err error) error {
	wrapped := fmt.Errorf("服务器 %d：P1 Vision 需要已安装且正在运行的轻舟修复内核 %s（含 with_v2ray_api）；当前内核校验失败：%w。无法确认逐用户链路就绪，请管理员手动确认或重启到修复内核后重试", id, sbver.VisionFramingFixVersion, err)
	if err := c.st.SetNodeSingboxError(id, wrapped.Error()); err != nil {
		wrapped = errors.Join(wrapped, fmt.Errorf("record version failure: %w", err))
	}
	if runtime, ok := c.st.(visionRuntimeStore); ok {
		if err := runtime.SetNodeVisionRuntimeError(id, wrapped.Error()); err != nil {
			wrapped = errors.Join(wrapped, fmt.Errorf("record live-core failure: %w", err))
		}
	}
	c.markVisionRetry(id)
	c.setStatus(id, "failed", wrapped.Error())
	return wrapped
}

func (c *Controller) verifyVisionCapability(ctx context.Context, id int64, sv *store.Server, installed bool) error {
	remote := sv != nil && !isLocalHostContext(ctx, sv.Host)
	if remote {
		if c.remoteMgr == nil {
			return c.visionProbeFailure(id, fmt.Errorf("remote manager unavailable"))
		}
		if installed {
			if err := c.acquireRemote(ctx); err != nil {
				return c.visionProbeFailure(id, err)
			}
			defer c.releaseRemote()
		}
	}
	if installed {
		var out string
		var err error
		if remote {
			// Also rediscover paths: a long-lived path cache must not mask replacement.
			c.remoteMgr.ForgetSingBoxBin(id)
			_, out, err = c.remoteMgr.SupportsStatsAPI(ctx, SSHConfigFor(sv))
		} else if sv == nil {
			if reporter, ok := c.mgr.(VersionReporter); ok {
				out, err = reporter.Version(ctx)
			} else {
				err = fmt.Errorf("installed version reporter unavailable")
			}
		} else {
			var bin string
			bin, err = resolveSingBoxBin(sv.SingBoxBin)
			if err == nil {
				var raw []byte
				cmd := exec.CommandContext(ctx, bin, "version")
				cmd.WaitDelay = 2 * time.Second
				raw, err = cmd.Output()
				out = string(raw)
			}
		}
		if err != nil {
			return c.visionProbeFailure(id, err)
		}
		info := sbver.Parse(out)
		if !info.HasVisionFramingFix || !info.HasV2RayAPI {
			probeErr := fmt.Errorf("installed binary lacks the exact Vision framing fix marker or v2ray_api (version %q)", info.Version)
			if err := c.st.SetNodeSingbox(id, info); err != nil {
				probeErr = errors.Join(probeErr, err)
			}
			return c.visionProbeFailure(id, probeErr)
		}
	}
	out, err := c.inspectRunningVisionVersion(ctx, sv)
	if err != nil {
		return c.visionProbeFailure(id, err)
	}
	info := sbver.Parse(out)
	if err := c.st.SetNodeSingbox(id, info); err != nil {
		return c.visionProbeFailure(id, err)
	}
	if !info.HasVisionFramingFix || !info.HasV2RayAPI {
		return c.visionProbeFailure(id, fmt.Errorf("running executable lacks the exact Vision framing fix marker or v2ray_api (version %q)", info.Version))
	}
	if runtime, ok := c.st.(visionRuntimeStore); ok {
		if err := runtime.SetNodeVisionRuntime(id, info); err != nil {
			return c.visionProbeFailure(id, err)
		}
	}
	return nil
}

func (c *Controller) inspectRunningVisionVersion(ctx context.Context, sv *store.Server) (string, error) {
	ctx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	if sv != nil && !isLocalHostContext(ctx, sv.Host) {
		inspector, ok := c.remoteMgr.(interface {
			InspectManagedVersion(context.Context, *sshctl.ServerConfig) (string, error)
		})
		if !ok {
			return "", fmt.Errorf("remote running-version inspection unavailable")
		}
		return inspector.InspectManagedVersion(ctx, SSHConfigFor(sv))
	}
	path := c.localConfigPath()
	if sv != nil {
		path = serverConfigPath(sv)
	}
	// Allows isolated process-boundary fakes without shelling into the host.
	if inspector, ok := c.mgr.(interface {
		InspectManagedVersion(context.Context, string, string) (string, error)
	}); ok {
		return inspector.InspectManagedVersion(ctx, c.trafficUnit(sv), path)
	}
	return sbproc.InspectManagedVersion(ctx, c.trafficUnit(sv), path)
}
